version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["sh", "-c", "yarn prisma migrate deploy && yarn prisma generate && yarn dev"]
    


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: water_gas_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
